spring.application.name=PP_3_1_2_Boot_Security

# === Подключение к БД ===
spring.datasource.url=jdbc:mysql://localhost:3306/security_db?useSSL=false&serverTimezone=UTC&sessionVariables=FOREIGN_KEY_CHECKS=0
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.hbm2ddl.extra_physical_table_types=VIEW

# === Thymeleaf ===
spring.thymeleaf.enabled=true

# === Logging (SLF4J) ===
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

#server.error.whitelabel.enabled=false